import pandas as pd
import matplotlib.pyplot as plt
import os

def plot_wave_components(csv_file):
    # Read the CSV file
    df = pd.read_csv(csv_file)

    # Create a figure with 3 subplots for each dimension
    fig, axes = plt.subplots(3, 3, figsize=(18, 12))
    fig.suptitle(f'Wave Components Analysis: {os.path.basename(csv_file)}', fontsize=16)

    # Time array
    time = df['time']

    # Plot X dimension components
    axes[0, 0].plot(time, df['acc_x'], label='a_x', color='r')
    axes[0, 0].set_ylabel('Acceleration (m/s²)')
    axes[0, 0].set_title('X Dimension')
    axes[0, 0].grid(True)

    axes[1, 0].plot(time, df['vel_x'], label='v_x', color='g')
    axes[1, 0].set_ylabel('Velocity (m/s)')
    axes[1, 0].grid(True)

    axes[2, 0].plot(time, df['disp_x'], label='x', color='b')
    axes[2, 0].set_ylabel('Displacement (m)')
    axes[2, 0].set_xlabel('Time (s)')
    axes[2, 0].grid(True)

    # Plot Y dimension components
    axes[0, 1].plot(time, df['acc_y'], label='a_y', color='r')
    axes[0, 1].set_title('Y Dimension')
    axes[0, 1].grid(True)

    axes[1, 1].plot(time, df['vel_y'], label='v_y', color='g')
    axes[1, 1].grid(True)

    axes[2, 1].plot(time, df['disp_y'], label='y', color='b')
    axes[2, 1].set_xlabel('Time (s)')
    axes[2, 1].grid(True)

    # Plot Z dimension components
    axes[0, 2].plot(time, df['acc_z'], label='a_z', color='r')
    axes[0, 2].set_title('Z Dimension')
    axes[0, 2].grid(True)

    axes[1, 2].plot(time, df['vel_z'], label='v_z', color='g')
    axes[1, 2].grid(True)

    axes[2, 2].plot(time, df['disp_z'], label='z', color='b')
    axes[2, 2].set_xlabel('Time (s)')
    axes[2, 2].grid(True)

    # Add legends
    for ax_row in axes:
        for ax in ax_row:
            ax.legend()

    plt.tight_layout()
    plt.show()

# Example usage with the test files from your code
if __name__ == "__main__":
    # List of CSV files generated by the test cases
    csv_files = [
        "short_waves.csv",
        "medium_waves.csv",
        "long_waves.csv"
    ]

    # Plot each file
    for file in csv_files:
        try:
            plot_wave_components(file)
        except FileNotFoundError:
            print(f"File {file} not found. Skipping...")
